target: fetch1 fetch2 fetch3 fetch4 final
final:
	./print_results.sh
fetch1:
	./curl25times.sh > out1.txt
fetch2:
	./curl25times.sh > out2.txt
fetch3:
	./curl25times.sh > out3.txt
fetch4:
	./curl25times.sh > out4.txt
